services:
  postgres:
    image: postgres:17
    restart: always
    env_file: stack.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    network_mode: service:ts-postgres
  ts-postgres:
    image: tailscale/tailscale:latest
    container_name: ts-postgres
    hostname: postgres.warthog-trout.ts.net
    restart: unless-stopped
    volumes:
      - ts-postgres:/var/lib/tailscale
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_HOSTNAME: postgres
      TS_STATE_DIR: /var/lib/tailscale

  litellm:
    image: ghcr.io/berriai/litellm-database:main-latest
    environment:
      PROXY_BASE_URL: http://litellm.warthog-trout.ts.net:4000
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres.warthog-trout.ts.net:5432/${POSTGRES_DB}"
      STORE_MODEL_IN_DB: "True"
      LITELLM_LOCAL_MODEL_COST_MAP: "True"
      LITELLM_DROP_PARAMS: "True"
    env_file: stack.env
    restart: unless-stopped
    network_mode: service:ts-litellm
  ts-litellm:
    image: tailscale/tailscale:latest
    container_name: ts-litellm
    hostname: litellm.warthog-trout.ts.net
    restart: unless-stopped
    volumes:
      - ts-litellm:/var/lib/tailscale
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_HOSTNAME: litellm
      TS_STATE_DIR: /var/lib/tailscale


  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    restart: unless-stopped
    environment:
      WEBUI_URL: http://ai.warthog-trout.ts.net
    volumes:
      - open-webui:/app/backend/data    
    network_mode: service:ts-open-webui
  ts-open-webui:
    image: tailscale/tailscale:latest
    container_name: ts-open-webui
    hostname: open-webui.warthog-trout.ts.net
    restart: unless-stopped
    volumes:
      - ts-open-webui:/var/lib/tailscale
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_HOSTNAME: open-webui
      TS_STATE_DIR: /var/lib/tailscale

volumes:
  ts-postgres:
  postgres_data:

  ts-open-webui:
  open-webui:

  ts-litellm: